name: Build and Publish Default Docker Image

on: 
  workflow_dispatch:
  push:
    branches: [ singularity-compatible ]
  pull_request:
    branches: [ singularity-compatible ]

jobs:
  build_tensorflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish TensorFlow Docker
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        TensorFlow_Version: '2.10.0'
        TensorFlow_Variants: '-gpu'
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: TensorFlow/
        tag: "tensorflow-${{ env.TensorFlow_Version }}${{ env.TensorFlow_Variants }}-singularity"
        no_push: ${{ github.event_name == 'pull_request' }}

  build_pytorch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish Pytorch Docker
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        PyTorch_Version: '1.13.0-cuda11.6-cudnn8'
        PyTorch_Variants: '-runtime'
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: PyTorch/
        tag: "pytorch-${{ env.PyTorch_Version }}${{ env.PyTorch_Variants }}-singularity"
        no_push: ${{ github.event_name == 'pull_request' }}
