name: Build and Publish Docker Images

on: [ push ]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "singularity-compatible"
