name: Build and Publish Default Docker Image

on: [ push ]
jobs:
  build_tensorflow_devel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish TensorFlow Docker
      uses: elgohr/Publish-Docker-Github-Action@2.13
      env:
        TensorFlow_Variants: '-devel-gpu'
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: TensorFlow/
        buildargs: "TensorFlow_Variants"
        tags: "tensorflow-latest-devel-gpu-singularity"

  build_tensorflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish TensorFlow Docker
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: TensorFlow/
        tags: "tensorflow-latest-gpu-singularity"

  build_pytorch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Pytorch Docker
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: PyTorch/
        tags: "pytorch-1.5-cuda10.1-cudnn7-runtime-singularity"
