name: Build and Publish Tensorflow Docker Image

on: 
  workflow_dispatch:
  push:
    branches: [ singularity-compatible ]
    paths: [ TensorFlow/Dockerfile, .github/workflows/tensorflow_image.yml ]
  pull_request:
    branches: [ singularity-compatible ]
    paths: [ TensorFlow/Dockerfile, .github/workflows/tensorflow_image.yml ]

jobs:
  build_tensorflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build TensorFlow Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        TensorFlow_Version: '2.12.0'
        TensorFlow_Variants: '-gpu'
      with:
        name: fnallpc/fnallpc-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TensorFlow_Version,TensorFlow_Variants
        workdir: TensorFlow/
        tags: "tensorflow-${{ env.TensorFlow_Version }}${{ env.TensorFlow_Variants }}-singularity"
        no_push: ${{ github.event_name == 'pull_request' }}
